### ISSUE TITLE
Complatable with Plex TV?

### ISSUE THREAD

**Issue by emeraldjava** [zakalibit/kodi.rteplayer.hq#2]
Hi,
I'm wondering do you have an opinion on how easy it might be to port this plugin to make it work as a Plex plugin. As i understand, Plex is build from the XBMC codebase so i believe it might be possible.
Regards,
P

**Comment by zakalibit** [comment]
I never did anything, or looked a plex, so the short answer is I don't know.

**Comment by zakalibit** [comment]
looked in to plex, I might try give it a go, not sure how long it will take.

**Comment by zakalibit** [comment]
first cut https://github.com/zakalibit/RTEPlayer.bundle
