### ISSUE TITLE
2048 v 1024

### ISSUE THREAD

**Issue by upandcumming** [zakalibit/kodi.rteplayer.hq#3]
Hi Alex,

First of all thank you for such fantastic addon. Such a great improvement.

One thing - is there a way from changing the default quality from 1048kbps to 2048kbps?

For example this link: http://cdn.rasset.ie/hls-vod/2016/0516/20160516_rtetwo-soccerrepu_cl10574055_10574056_260_drm_/20160516_rtetwo-soccerrepu_cl10574055_10574056_260_drm__1024k.mp4.m3u8 is the one played by Kodi. At the same time, this link: http://cdn.rasset.ie/hls-vod/2016/0516/20160516_rtetwo-soccerrepu_cl10574055_10574056_260_drm_/20160516_rtetwo-soccerrepu_cl10574055_10574056_260_drm__2048k.mp4.m3u8 will also work perfectly when played in Kodi.

Is there a way that this can be defaulted to 2048 rather 1024?

Thank you!

**Comment by zakalibit** [comment]
If you tell me what parameters I have to use in the request, as max I get in the playlist is 1024.

**Comment by zakalibit** [comment]
Looking at available platforms, looks like on UPS cable tv might be available, but I'd need to know what parameters UPC stb uses.

**Comment by zakalibit** [comment]
Please see plugin.video.rteplayer.hq-3.0.9.zip, or it should update automatically, I have hacked it in for now.
